const db = [
  { name: "Caitlyn", cost: 1, pool: 29 },
  { name: "Fiora", cost: 1, pool: 29 },
  { name: "Graves", cost: 1, pool: 29 },
  { name: "Illaoi", cost: 1, pool: 29 },
  { name: "Jarvan", cost: 1, pool: 29 },
  { name: "Leona", cost: 1, pool: 29 },
  { name: "Malphite", cost: 1, pool: 29 },
  { name: "Nocturne", cost: 1, pool: 29 },
  { name: "Poppy", cost: 1, pool: 29 },
  { name: "Twisted", cost: 1, pool: 29 },
  { name: "Xayah", cost: 1, pool: 29 },
  { name: "Ziggs", cost: 1, pool: 29 },
  { name: "Zoe", cost: 1, pool: 29 },
  { name: "Lucian", cost: 2, pool: 22 },
  { name: "Kog'Maw", cost: 2, pool: 22 },
  { name: "Ahri", cost: 2, pool: 22 },
  { name: "Blitzcrank", cost: 2, pool: 22 },
  { name: "Annie", cost: 2, pool: 22 },
  { name: "Darius", cost: 2, pool: 22 },
  { name: "Shen", cost: 2, pool: 22 },
  { name: "Rakan", cost: 2, pool: 22 },
  { name: "Nautilus", cost: 2, pool: 22 },
  { name: "Mordekaiser", cost: 2, pool: 22 },
  { name: "Xin", cost: 2, pool: 22 },
  { name: "Zed", cost: 2, pool: 22 },
  { name: "Yasuo", cost: 2, pool: 22 },
  { name: "Karma", cost: 3, pool: 18 },
  { name: "Jayce", cost: 3, pool: 18 },
  { name: "Bard", cost: 3, pool: 18 },
  { name: "Ashe", cost: 3, pool: 18 },
  { name: "Cassiopeia", cost: 3, pool: 18 },
  { name: "Ezreal", cost: 3, pool: 18 },
  { name: "Syndra", cost: 3, pool: 18 },
  { name: "Shaco", cost: 3, pool: 18 },
  { name: "Rumble", cost: 3, pool: 18 },
  { name: "Master", cost: 3, pool: 18 },
  { name: "Neeko", cost: 3, pool: 18 },
  { name: "Vi", cost: 3, pool: 18 },
  { name: "Vayne", cost: 3, pool: 18 },
  { name: "Jhin", cost: 4, pool: 12 },
  { name: "Jinx", cost: 4, pool: 12 },
  { name: "Gnar", cost: 4, pool: 12 },
  { name: "Irelia", cost: 4, pool: 12 },
  { name: "Fizz", cost: 4, pool: 12 },
  { name: "Soraka", cost: 4, pool: 12 },
  { name: "Riven", cost: 4, pool: 12 },
  { name: "Viktor", cost: 4, pool: 12 },
  { name: "Teemo", cost: 4, pool: 12 },
  { name: "Wukong", cost: 4, pool: 12 },
  { name: "Lulu", cost: 5, pool: 10 },
  { name: "Janna", cost: 5, pool: 10 },
  { name: "Aurelion", cost: 5, pool: 10 },
  { name: "Ekko", cost: 5, pool: 10 },
  { name: "Gangplank", cost: 5, pool: 10 },
  { name: "Urgot", cost: 5, pool: 10 },
  { name: "Thres,h", cost: 5, pool: 10 },
  { name: "Xerath", cost: 5, pool: 10 },
];

const Calc = (vars) => {
  return vars * 2;
};
export default Calc;
